#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: furushchev <furushchev@jsk.imi.i.u-tokyo.ac.jp>
# ROS2: outputs current device parameters as YAML for use with --params-file.

import os
import sys

from respeaker_ros.respeaker_node import PARAMETERS, RespeakerInterface


class _DummyLogger:
    def info(self, *a, **kw):
        pass

    def debug(self, *a, **kw):
        pass

    def warn(self, *a, **kw):
        pass


def main(outpath):
    try:
        respeaker = RespeakerInterface(logger=_DummyLogger())
    except RuntimeError as e:
        print('No device found or init failed: %s' % e)
        return 1
    lines = [
        "# Respeaker device parameters (generated by respeaker_gencfg.py)",
        "# Use: ros2 run respeaker_ros respeaker_node --ros-args --params-file %s" % outpath,
        "",
        "respeaker_node:",
        "  ros__parameters:",
    ]
    for key, val in PARAMETERS.items():
        type_, max_, min_, rw_ = val[2], val[3], val[4], val[5]
        if rw_ != 'rw':
            continue
        try:
            v = respeaker.read(key)
        except Exception:
            continue
        if type_ == 'int' and max_ == 1 and min_ == 0:
            lines.append("    %s: %s" % (key, 'true' if v else 'false'))
        elif type_ == 'int':
            lines.append("    %s: %d" % (key, int(v)))
        else:
            lines.append("    %s: %.6f" % (key, float(v)))
    respeaker.close()
    with open(outpath, 'w') as f:
        f.write('\n'.join(lines))
    os.chmod(outpath, 0o644)
    print("Saved parameters to %s" % outpath)
    return 0


def main_cli():
    if len(sys.argv) > 1:
        outpath = sys.argv[1]
    else:
        pkg_share = os.environ.get('AMENT_PREFIX_PATH', '').split(os.pathsep)[0]
        if pkg_share:
            outpath = os.path.join(pkg_share, 'share', 'respeaker_ros', 'config', 'respeaker_params.yaml')
        else:
            outpath = os.path.join(os.path.dirname(__file__), '..', 'config', 'respeaker_params.yaml')
    return main(outpath)


if __name__ == '__main__':
    sys.exit(main_cli())
